# Generated by Django 4.1.3 on 2022-12-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('employeeId', models.CharField(max_length=15)),
                ('personalNumber', models.CharField(max_length=15)),
                ('userComment', models.TextField(blank=True, null=True)),
                ('exceptionExpirationDate', models.DateField(blank=True, null=True)),
                ('hiddenRuleId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rule.hiddenrule')),
                ('positionRuleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.positionrule')),
                ('shiftRuleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.shiftrule')),
            ],
        ),
    ]
