# Generated by Django 4.1.3 on 2022-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('personalNumber', models.CharField(max_length=15)),
                ('userComment', models.TextField(blank=True, null=True)),
                ('exceptionExpirationDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
