# Generated by Django 4.1.3 on 2022-11-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinationType', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassedExaminations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('examinationTypeId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='examinationType.examinationtype')),
            ],
        ),
    ]
