# Generated by Django 4.1.3 on 2022-12-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.city')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ruleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.rule')),
            ],
        ),
        migrations.CreateModel(
            name='PositionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.department')),
                ('ruleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.rule')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rule.rule')),
            ],
        ),
    ]
